# -----------
# gam-student
# -----------
# A script to update student Google passwords via GAM after the nightly account sync process.
# Execute this script via Task Scheduler after the nightly student import.

import csv
import subprocess
from datetime import datetime

# Your student Google domain
student_domain = "student.sgate.k12.mi.us"

# Running log of GAM outputs
log_file = "C:\Scripts\GAM-Student\log.txt"

# The absolute path of the nightly difference .csv generated by the Student Import Script on the DC.
diff_file = "C:\StudentImport\data\diff.csv"

# The location of the GAM executable on the local system.
gam_file = "C:\GAM\gam.exe"

# The local file used by GAM for batch processing of students.
gam_batch = "C:\Scripts\GAM-Student\gam_student_batch.txt"

# Convert the diff file into a simple list.
with open(diff_file, 'rb') as f_diff:
    reader = csv.reader(f_diff)
    student_list = list(reader)
f_diff.close()

# We're only interested in the last two values of each entry (password & username respectively).
# Extract the values and generate a GAM batch file out of those.
f_batch = open(gam_batch, "w")

for item in range(len(student_list)):
    segment = student_list[item][-2:]
    student_password = segment[0]
    student_username = segment[1]
    gam_string = 'gam update user "' \
                 + student_username \
                 + '@' + student_domain + '" password "' \
                 + student_password + '"\n'
    f_batch.write(gam_string)

f_batch.close()

# Run GAM with the batch file's contents and save the output
f_log = open(log_file, "a")
f_log.write("\nStart of session @ " + str(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) + "\n")
f_log.flush()
subprocess.call([gam_file, "batch", gam_batch], stdin=None, stdout=f_log, stderr=None, shell=False)
f_log.write("End of session. \n\n")
f_log.close()
print("Appended log & exiting.")
